
name: Smart App -Smoke Tests
on:
push:
branches: [master]
  pull_request:
  branches: [master]

  jobs: 
     cypress-run:
     runs-on: ubuntu-latest
     steps: 
     -name: Checkout
     uses: actions/checkout@v4

     -name: Install Dependencies and Run Smoke Tests
     with:
           browser: chrome
           headed: false
           command: npm run test:smoke

        

     